# .cz.yaml
path: cz-conventional

cz-conventional:
  types:
    - type: feat
      description: A new feature
    - type: fix
      description: A bug fix
    - type: docs
      description: Documentation only changes
    - type: style
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - type: refactor
      description: A code change that neither fixes a bug nor adds a feature
    - type: perf
      description: A code change that improves performance
    - type: test
      description: Adding missing tests or correcting existing tests
    - type: chore
      description: Changes to the build process or auxiliary tools and libraries such as documentation generation

  scopes:
    - scope: api
    - scope: ui
    - scope: db

  messages:
    type: "Select the type of change you are committing:"
    scope: "Denote the scope of this change (optional):"
    subject: "Write a short, imperative tense description of the change (max 100 chars):"
    body: "Provide a longer description of the change (optional):"
    footer: "List any breaking changes or issues closed by this change (optional):"
